ALTER TABLE usuarios ADD data_criacao DATETIME2 DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE usuarios ADD data_atualizacao DATETIME2 DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE usuarios ADD ativo BIT DEFAULT 1;

ALTER TABLE motos ADD data_criacao DATETIME2 DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE motos ADD data_atualizacao DATETIME2 DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE motos ADD ativo BIT DEFAULT 1;
