ALTER TABLE usuarios ADD COLUMN data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE usuarios ADD COLUMN data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE usuarios ADD COLUMN ativo BOOLEAN DEFAULT TRUE;

ALTER TABLE motos ADD COLUMN data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE motos ADD COLUMN data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE motos ADD COLUMN ativo BOOLEAN DEFAULT TRUE;
